// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlZpEnINPch5IZO83XOZMWYaNxSp1DFy0',
    appId: '1:121279539155:web:cc663a3646f5053a707126',
    messagingSenderId: '121279539155',
    projectId: 'sikades-pp',
    authDomain: 'sikades-pp.firebaseapp.com',
    storageBucket: 'sikades-pp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPwtEuGPHPCJLP-rr1Lk9_cqaM3Vr34To',
    appId: '1:121279539155:android:671e7a16943897b7707126',
    messagingSenderId: '121279539155',
    projectId: 'sikades-pp',
    storageBucket: 'sikades-pp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfySYWgiAKkGXuVp6tHHnmR6bE0f9pwGM',
    appId: '1:121279539155:ios:20f618b5a3e665f8707126',
    messagingSenderId: '121279539155',
    projectId: 'sikades-pp',
    storageBucket: 'sikades-pp.appspot.com',
    iosClientId: '121279539155-2bqks27qotgshbbllgpmf7nqbt3tje77.apps.googleusercontent.com',
    iosBundleId: 'com.example.sikades',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfySYWgiAKkGXuVp6tHHnmR6bE0f9pwGM',
    appId: '1:121279539155:ios:8aa26ba4bb15a3eb707126',
    messagingSenderId: '121279539155',
    projectId: 'sikades-pp',
    storageBucket: 'sikades-pp.appspot.com',
    iosClientId: '121279539155-4kjti64uu4uv8u1n4k4vev8e8nski0vu.apps.googleusercontent.com',
    iosBundleId: 'com.example.sikades.RunnerTests',
  );
}
